Add epidemic risk vignette and `probability_contain()`
epiverse-trace/superspreading pull request #24
Opened 2023-06-08 15:45 UTC by joshwlambert

This PR addresses #12 (and makes a start on #13). 

The primary focus of this PR is to add a vignette that discusses the application of {superspreading} functions to decision making and policy. This takes inspiration from the document initially shared in #5 and mentioned in #12 which is a preprint used by SAGE during the COVID-19 pandemic.

As part of this vignette on control measures, a new function was added: `probability_contain()`. This implements population-level control measures. It does not complete the requirements of #13 which also requires individual level control and may relate to development from epiverse-trace/epichains#3.

Tests and documentation are added for `probability_contain()`. {bpmodels} is added as a remote dependency, and {ggtext} as a suggested dependency.

2023-06-08 17:52 UTC, jamesmbaazam requested changes
This is a nice vignette to illustrate a use case for the package. I've suggested a few changes that should be straightforward to fix.

2023-06-08 17:52 UTC, jamesmbaazam commented on R/probability_contain.R
> +probability_contain <- function(R, k, a = 1, c, # nolint
Please document `a`.

Also include checks for `0 =< c <= 1`.

2023-06-08 17:52 UTC, jamesmbaazam commented on vignettes/epidemic_risk.Rmd
> +clusters can provide insight into the occurrence of superspreading events and from this
I suggest to define "transmission clusters" and "superspreading events". This is a good place for beginners to learn about the subject.

2023-06-08 17:52 UTC, jamesmbaazam commented on vignettes/epidemic_risk.Rmd
> +clusters can provide insight into the occurrence of superspreading events and from this
```suggestion
clusters and heterogeneity in individual-level transmission can provide insight into the occurrence of superspreading events and from this
```

2023-06-12 10:21 UTC, joshwlambert commented on R/probability_contain.R
> +probability_contain <- function(R, k, a = 1, c, # nolint
`a` is documented by inheriting from `probability_epidemic()`

2023-06-12 10:29 UTC, joshwlambert commented on R/probability_contain.R
> +probability_contain <- function(R, k, a = 1, c, # nolint
Resolved in b971d7b237888ea6792368a1b31e26ff4a39c926

2023-06-12 10:40 UTC, joshwlambert commented on vignettes/epidemic_risk.Rmd
> +clusters can provide insight into the occurrence of superspreading events and from this
Added link to getting started vignette which includes more introductory content and definitions in ff0b6f2753a6ed75107f41a9610816bd0c1caf9d

2023-06-12 10:51 UTC, joshwlambert commented on vignettes/epidemic_risk.Rmd
> +transmission variability have been reported, either for this outbreak or a previous outbreak
At least from what I've seen from COVID, MERS, Ebola and other recent outbreaks, this sort of analysis is routine.

2023-06-12 10:57 UTC, joshwlambert commented on vignettes/epidemic_risk.Rmd
> +The degree of variability in transmission increases as $k$ decreases. So the probability
Add citation in 32cf43213e2a172584039b26bd27b08762b64428

2023-06-12 10:57 UTC, joshwlambert commented
Thanks for the comments @jamesmbaazam!

2023-06-13 11:46 UTC, jamesmbaazam approved these changes

2023-06-13 12:30 UTC, merged